Bulgarian Language added
flore2003/staythefuckhome pull request #82
Opened 2020-03-16 21:55 UTC by ddachkinov

2020-03-16 22:08 UTC, phelmig commented
Hi @ddachkinov,
Thank you for your translation. Since we can't validate the contribution's quality we are currently requiring all translations to be reviewed by at least two native speakers (we count you as the contributor as the first). If everything is fine, a simple comment on this pull request is sufficient. If you can reach out to your personal network to find someone for a peer review it would be highly appreciated.

2020-03-16 23:05 UTC, nstankovicc commented
Native Bulgarian here. I am picking up review.

2020-03-16 23:08 UTC, Nikoogle commented
Native Bulgarian here. I will gladly review.

2020-03-16 23:09 UTC, Nikoogle commented on site/bg.njk
> +lang: en
Needs to be:
`bg`

2020-03-16 23:11 UTC, Nikoogle commented on site/bg.njk
> +meta_description: Нашите правителства не могат да се справят без нашата помощ, трябва да предприемем действия сега! Изпълнете своята роля и останете у дома мамка му!
Нашите правителства не могат да се справят без нашата помощ, трябва да предприемем действия сега! Изпълнете своята роля и **си стойте вкъщи, мамка му!**

2020-03-16 23:11 UTC, Nikoogle commented on site/bg.njk
> +meta_title: кампания за спирането на пандемията COVID-19
Главни букви.
**К**ампания...

2020-03-16 23:13 UTC, Nikoogle commented on site/bg.njk
> +                вируса и разрастване на <a href="https://en.wikipedia.org/wiki/Coronavirus_disease_2019">COVID-19 пандемията</a>.
Let's use the Bulgarian version of the article -- [Here](https://bg.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81%D0%BD%D0%B0_%D0%B1%D0%BE%D0%BB%D0%B5%D1%81%D1%82_2019)

2020-03-16 23:31 UTC, Nikoogle requested changes
I am kindly requesting changes to this branch.
I have forwarded the same for review by fellow Bulgarian Native Speakers.

Thank you for your contribution. It's a great effort 👍

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <a href="https://en.wikipedia.org/wiki/Severe_acute_respiratory_syndrome_coronavirus_2">SARS-CoV-2</a>
Let's use the BG version of the article -- [Here](https://bg.wikipedia.org/wiki/SARS-CoV-2)

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Нереагирането навреме, успокояването на масата и стремежът им да стабилизират икономиката ги възпират да предприемат
Word Choice.

Липсата на реакция, вместо Нереагирането Навреме.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Време е ние, като граждани на тази Земя, да предприемем действия сега и да дадем своята роля в борбата с COVID-19.
Word Choice.

Да дадем своя принос, вместо да дадем своята роля.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Да си го кажем директно: <strong>Стойте си у дома мамка му!</strong>
Missing comma.

Стойте си у дома**,**мамка му!

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                коронавирус пандемията е да се понижат неговите шансове за разпространение. Следният списък с действия, подредени от
Word Choice.

...неговите шансове за разпространение --> Шансовете на вируса за разпространение.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Най-лесните за прилагане към най-ефективните съвете в борбата срещу пандемията. Той трябва да служи като набор от насоки за хората, които желаят да се присъединят
Typo + Comma.
Най-лесните за прилагане към най-ефективните съвете в борбата срещу пандемията. --> Най-лесните за прилагане, към най-ефективните съвет**И**, в борбата срещу пандемията.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                къв кампанията и предприемат действия, от които ще имат огромно значение.
Typo + Comma + Word Choice.
 
къ**М** кампанията, и предприемат действия, които са истински значими.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <li class="pb-2">Мийте си ръцете често и спазвайте етикет при кашляне и кихане (Използвайте лакът).</li>
Adding Context.
(Използвайте лакът) --> (Използвайте лактите си, а не ръце).

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <li class="pb-2">Докосвайти лицето си възможно най-малко, включително устата, носът и очите си.</li>
Typo.
ДокосвайтИ -> Докосвайт**е**

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <li class="pb-2">Практикувайте социално дистанциране, без прегръдки и целувки, без ръкостискания, без High 5 (гепи). Ако трябва, използвайте по-безопасни алтернативи. </li>
High 5 -> (Забиване/Даване на 5).

Let's translate this fully, w/o doing a bg-eng mix.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <li class="pb-2">Стойте далеч от социални събития и събития, като срещи в клуба, религиозни служби и частни партита. </li>
Missing punctuation, that creates logical separation between parts of the sentence.

Стойте далеч от социални събития**,**  и събития,

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Поради близките симптоми и привидно сходните усложнения, съвсем естествено е хората да ги бъркат
I think we should add a comma after "бъркат." And start the next sentence on a new line. It's too wordy.

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                        Докато при повечето заразени хора ще отмине само с леки симптоми, липсата на имунитет у хората може да доведе до тежки заболявания при значителен брой рискови индивиди - нашит
Missing clarification, going out of context.

Докато при повечето заразени хора **инфекцията** ще отмине...

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                        може да доведе до невероятно високи числа за доста кратък период от време. С удвоилият се само за няколко дни брой на заразените хора<sup><a class="source-link" href="https://
Missing linking word.

...**Той**(растежа) може...

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                Присъединявайки се към кампанията и следователно ограничавате възможностите за нови инфекции, вие не само защитавате себе си, но и помагате за ограничаване на разпространението за вси
...и следователно **ограничавайки**...

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="I will do my part in the fight against #COVID19. I urge you to do the
I will do my part in the fight against #COVID19. I urge you to do the same!

"Аз ще направя всичко необходимо, за да преборим #COVID19. Приветствам Ви да направите същото!

2020-03-16 23:31 UTC, Nikoogle commented on site/bg.njk
> +                В момента получаваме много имейли, така че може да не се свържем веднага с вас.
...с вас веднага...

2020-03-16 23:32 UTC, dachkinova commented
As a native speaker, I would say that the translation is accurate and complete

2020-03-17 13:02 UTC, ddachkinov commented on site/bg.njk
> +                Поради близките симптоми и привидно сходните усложнения, съвсем естествено е хората да ги бъркат
reworded it differently, to be less wordy

2020-03-17 13:10 UTC, ddachkinov commented on site/bg.njk
> +                В момента получаваме много имейли, така че може да не се свържем веднага с вас.
Thank you for your time and suggestions, I've made the corrections and I'm submitting the code. 
Stay safe!

2020-03-17 13:18 UTC, ddachkinov commented
Thank you for your time and suggestions, I've made the corrections and I've committed the file.
Stay safe everyone!

2020-03-18 00:20 UTC, Nikoogle approved these changes
Thank you, looks good!

2020-03-21 19:26 UTC, Nikoogle commented
@phelmig.

This has been approved by two reviewers.
Can you please check it out?

2020-06-13 19:31 UTC, ddachkinov commented
Can you check it out @phelmig, it has been 3 months now, it would have been nice for some folks to read it.

2022-08-18 11:38 UTC, closed without merging